<?php
declare(strict_types=1);

// HubspotAuth SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

HubspotAuthUtility::setRegistrar(function (HubspotAuthUtility $u): void {
    $u->clean = [HubspotAuthClean::class, 'call'];
    $u->done = [HubspotAuthDone::class, 'call'];
    $u->make_error = [HubspotAuthMakeError::class, 'call'];
    $u->feature_add = [HubspotAuthFeatureAdd::class, 'call'];
    $u->feature_hook = [HubspotAuthFeatureHook::class, 'call'];
    $u->feature_init = [HubspotAuthFeatureInit::class, 'call'];
    $u->fetcher = [HubspotAuthFetcher::class, 'call'];
    $u->make_fetch_def = [HubspotAuthMakeFetchDef::class, 'call'];
    $u->make_context = [HubspotAuthMakeContext::class, 'call'];
    $u->make_options = [HubspotAuthMakeOptions::class, 'call'];
    $u->make_request = [HubspotAuthMakeRequest::class, 'call'];
    $u->make_response = [HubspotAuthMakeResponse::class, 'call'];
    $u->make_result = [HubspotAuthMakeResult::class, 'call'];
    $u->make_point = [HubspotAuthMakePoint::class, 'call'];
    $u->make_spec = [HubspotAuthMakeSpec::class, 'call'];
    $u->make_url = [HubspotAuthMakeUrl::class, 'call'];
    $u->param = [HubspotAuthParam::class, 'call'];
    $u->prepare_auth = [HubspotAuthPrepareAuth::class, 'call'];
    $u->prepare_body = [HubspotAuthPrepareBody::class, 'call'];
    $u->prepare_headers = [HubspotAuthPrepareHeaders::class, 'call'];
    $u->prepare_method = [HubspotAuthPrepareMethod::class, 'call'];
    $u->prepare_params = [HubspotAuthPrepareParams::class, 'call'];
    $u->prepare_path = [HubspotAuthPreparePath::class, 'call'];
    $u->prepare_query = [HubspotAuthPrepareQuery::class, 'call'];
    $u->graphql_body = [HubspotAuthGraphql::class, 'body'];
    $u->graphql_errors = [HubspotAuthGraphql::class, 'errors'];
    $u->result_basic = [HubspotAuthResultBasic::class, 'call'];
    $u->result_body = [HubspotAuthResultBody::class, 'call'];
    $u->result_headers = [HubspotAuthResultHeaders::class, 'call'];
    $u->transform_request = [HubspotAuthTransformRequest::class, 'call'];
    $u->transform_response = [HubspotAuthTransformResponse::class, 'call'];
});
